version: '3'
services:
  nginx:
    image: honvid/nginx
    container_name: nginx
    restart: unless-stopped
    tty: true
    ports:
      - "8080:80"
    volumes:
      - ./:/home/app
      - ./dev/docker/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-fpm
      - mysql
      - redis
    networks:
      - backend

  php-fpm:
    image: honvid/php-fpm:dev
    container_name: php-fpm
    restart: unless-stopped
    tty: true
    ports:
      - "9000:9000"
    volumes:
      - ./:/home/app
    depends_on:
      - mysql
      - redis
    networks:
      - backend

  node:
    image: node:alpine
    working_dir: /app
    volumes:
      - ./:/app
    entrypoint: /app/dev/docker/entrypoint.node.sh

  mailhog:
    image: mailhog/mailhog
    ports:
      - ${DEV_MAIL_PORT:-8025}:8025

  redis:
    image: redis
    container_name: redis
    restart: unless-stopped
    tty: true
    ports:
      - "26379:6379"
    networks:
      - backend

  mysql:
    image: mysql
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - "9306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./database/data/mysql:/var/lib/mysql
    networks:
      - backend

networks:
  backend:
    driver: bridge